GET http://localhost:3000/api/usuarios

###

GET http://localhost:3000/api/categorias

###

GET http://localhost:3000/api/productos

###

GET http://localhost:3000/api/pedidos

###

POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "nombre": "Audifonos bluetooth",
    "categoria": "Tecnologia",
    "precio": 85000,
    "stock": 10,
    "activo": true,
    "proveedor": {
        "nombre": "TecnoProveedor",
        "nit": "900111222-1"
    },
    "comentarios": []
}

###

POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Deportes",
    "descripcion": "Articulos deportivos y accesorios"
}
